DROP TABLE IF EXISTS USER_ACTIVITY;
DROP TABLE IF EXISTS USER_TAB;
DROP TABLE IF EXISTS ROLE_TAB;

CREATE TABLE ROLE_TAB(
  role_id VARCHAR(250) PRIMARY KEY,
  role_name VARCHAR(250) NOT NULL
);

CREATE TABLE USER_TAB(
  username VARCHAR(250) PRIMARY KEY,
  password VARCHAR(250) NOT NULL,
  email VARCHAR(100) NOT NULL,
  firs_tname VARCHAR(250) NOT NULL,
  last_name VARCHAR(250),
  date_of_birth DATE,
  role_id VARCHAR(250) REFERENCES ROLE_TAB(role_id)
);


CREATE TABLE USER_ACTIVITY(
    activity_id VARCHAR(250) PRIMARY KEY,
    username VARCHAR(250) REFERENCES USER_TAB(username),
    activity_type VARCHAR(500) NOT NULL,
    activity_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

